// Tests the distribution generated by Java's Math.random() function.

import java.math.BigDecimal;

public  class  TestRandom {
	public static void main(String[]  args) {
        int run_limit = Integer.parseInt(args[0]);
		int count = 0;
		int over = 0;
		int under = 0;
		while(count<run_limit)
		{
			double ran = Math.random();
			if (ran<=0.5)
			{
				under++;
			}
			else
			{
				over++;
			}
			count++;
		}
		if (over==0 || under==0)
		{
			System.out.println("> 0.5: " + over + " times");
			System.out.println("<= 0.5: " + under + " times");
		}
		else
		{	
			if (over<under)
			{
				BigDecimal ratio = new BigDecimal((double)over/(double)under);
				System.out.println("> 0.5: " + over + " times");	
				System.out.println("<= 0.5: " + under + " times");
				System.out.println("ratio: " + ratio);
			}
			else 
			{
				BigDecimal ratio = new BigDecimal((double)under/(double)over);
				System.out.println("> 0.5: " + over + " times");	
				System.out.println("<= 0.5: " + under + " times");
				System.out.println("ratio: " + ratio);
			}
		}
	}
}
